config/routes.rb
Rails.application.routes.draw do
  resources :produtos
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'produtos#index'
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/produto.rb
class Produto < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/produtos_controller.rb
class ProdutosController < ApplicationController
  before_action :set_produto, only: %i[ show edit update destroy ]

  # GET /produtos or /produtos.json
  def index
    @produtos = Produto.all
  end

  # GET /produtos/1 or /produtos/1.json
  def show
  end

  # GET /produtos/new
  def new
    @produto = Produto.new
  end

  # GET /produtos/1/edit
  def edit
  end

  # POST /produtos or /produtos.json
  def create
    @produto = Produto.new(produto_params)

    respond_to do |format|
      if @produto.save
        format.html { redirect_to produto_url(@produto), notice: "Produto was successfully created." }
        format.json { render :show, status: :created, location: @produto }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @produto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /produtos/1 or /produtos/1.json
  def update
    respond_to do |format|
      if @produto.update(produto_params)
        format.html { redirect_to produto_url(@produto), notice: "Produto was successfully updated." }
        format.json { render :show, status: :ok, location: @produto }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @produto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /produtos/1 or /produtos/1.json
  def destroy
    @produto.destroy

    respond_to do |format|
      format.html { redirect_to produtos_url, notice: "Produto was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_produto
      @produto = Produto.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def produto_params
      params.require(:produto).permit(:modelo, :valor, :peso, :pedra, :metal, :descricao)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/produtos_helper.rb
module ProdutosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RubyJoias</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
    <body>
    <div class="central">
      <nav class="navbar navbar-expand-lg bg-dark">
          <div class="container">
            <a class="navbar-brand text-white" href="/produtos"><strong>RUBY</strong> JOIAS</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
              <ul class="navbar-nav">
                <li class="nav-item">
                  <%= link_to "Cadastrar produto", new_produto_path, {:class => "btn btn-outline-success"} %>
                </li>
              </ul>
            </div>
          </div>
        </nav>
      <div class="container">
          <main>
              <%= yield %>
          </main>
      </div>
  </body>
</html>

app/views/produtos/_form.html.erb
<%= form_with(model: produto) do |form| %>
  <% if produto.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(produto.errors.count, "error") %> prohibited this produto from being saved:</h2>

      <ul>
        <% produto.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :modelo, style: "display: block" %>
    <%= form.text_field :modelo, :class => "form-control" %>
  </div>

  <div>
    <%= form.label :valor, style: "display: block" %>
    <%= form.number_field :valor, :class => "form-control" %>
  </div>

  <div>
    <%= form.label :peso, style: "display: block" %>
    <%= form.number_field :peso, :class => "form-control" %>
  </div>

  <div>
    <%= form.label :pedra, style: "display: block" %>
    <%= form.text_field :pedra, :class => "form-control" %>
  </div>

  <div>
    <%= form.label :metal, style: "display: block" %>
    <%= form.text_field :metal, :class => "form-control" %>
  </div>

  <div>
    <%= form.label :descricao, style: "display: block" %>
    <%= form.text_area :descricao, :class => "form-control" %>
  </div>

  <div class="mt-4">
    <%= form.submit "Salvar", :class => "btn btn-success" %>
    <%= link_to "Voltar", produtos_path, {:class => "btn btn-outline-info"} %>
  </div>
<% end %>

app/views/produtos/_produto.html.erb
<div class="row mt-5">
  <div class="col-sm p-1">
    <table class="table table-striped">
        <tr>
          <th class="w-25"scope="col">Modelo</th>
          <td><%= produto.modelo %></td>
        </tr>
        <tr>
          <th scope="row">Valor</th>
          <td><%= produto.valor %></td>
        </tr>
        <tr>
          <th scope="row">Peso</th>
          <td><%= produto.peso %></td>
        </tr>
        <tr>
          <th scope="row">Metal</th>
          <td><%= produto.metal %></td>
        </tr>
        <tr>
          <th scope="row">Pedra</th>
          <td><%= produto.pedra %></td>
        </tr>
        <tr>
          <th scope="row">Descrição</th>
          <td><%= produto.descricao %></td>
        </tr>
      </tbody>
    </table>
  </div>

app/views/produtos/edit.html.erb
<h1>Editing produto</h1>

<%= render "form", produto: @produto %>

<br>

app/views/produtos/index.html.erb
<p style="color: green"><%= notice %></p>


<div class="row mb-5">
  <% @produtos.each do |produto| %>
    <div class="col-md-3">
      <div class="card mb-3">
        <div class="card-body">
          <h5 class="card-title"><%= produto.modelo %></h5>
          <h6 class="card-subtitle mb-2 text-muted"><%= produto.metal %></h6>
          <p class="card-text"><%= produto.valor %></p> 
          <%= link_to "Ver detalhes", produto, {:class => "btn btn-outline-success"} %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/produtos/new.html.erb
<h1 class="mt-4">Novo produto</h1>

<%= render "form", produto: @produto %>

<br>

app/views/produtos/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @produto %>

<div class="row mt-4">
  <div class="col-4">
    <ul class="list-group">
      <div class="btn-group" role="group" aria-label="Exemplo básico">
        <%= link_to "Voltar para produtos", produtos_path, {:class => "btn btn-outline-success"} %>
        <%= link_to "Editar produto", edit_produto_path(@produto), {:class => "btn btn-outline-info"} %>
      </div>
    </ul>
  </div>
  <div class="col-2">
    <ul class="list-group">
        <%= button_to "Deletar", @produto, {:class => "btn btn-outline-danger", method: :delete} %>
    </ul>
  </div>
</div>